version: "3.7"
services:
  app:
    container_name: "app"
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    networks:
      - custom

  web:
    container_name: "web"
    image: nginx
    depends_on:
      - app
    ports:
      - "8082:82"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - custom

networks:
  custom:
    name: custom
    driver: bridge

# https://www.youtube.com/watch?v=hhWouNy85gg