version: "3.7"
services:
  app:
    container_name: "app"
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - custom

  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./vol_api/conf.d:/etc/nginx/conf.d
    networks:
      - custom

networks:
  custom:
    name: custom
    driver: bridge

# https://www.youtube.com/watch?v=hhWouNy85gg